### ISSUE TITLE
Options Window Constantly Resizes

### ISSUE THREAD

**Issue by eliptus-google** [sdefresne/gerrit-monitor#4] opened 2019-04-19 11:05 UTC
When enough servers are added to cause a scrollbar to appear in the options window, the window constantly cycles between two sizes, one with a scrollbar and one without.

**Comment by nfischer** [comment] 2019-04-23 18:38
I'm also hitting this. The "cycling" is a really bad UX, because all the UI elements (checkboxes, input fields) are jittering around, making them impossible to click. This is blocking me from taking full advantage of the extension, because I simply can't add one of my gerrit instances to the UI.

**Comment by sdefresne** [comment] 2019-09-09 13:13
The extension does nothing fancy when presenting the option. The decision to display scrollbar is taken by Chrome itself (probably based on how much screen space is available).

I've tried adding many servers (up to 30) and I do see the scrollbar appears. However, for me, they are consistently showing. I do not experience any unstable state where the windows constantly resizes. As I cannot reproduce, any fix that I'll make will be speculative.

I'll try to change the css of the option page to always display the scrollbar. This should prevent the cycling between the two state with and without scrollbar (as there will always be a scrollbar).

**Comment by sdefresne** [comment] 2019-09-09 13:18
This should (hopefully) be fixed with version 1.0.6.

**Closed by sdefresne** 2019-09-09 13:18 UTC

**Comment by nfischer** [comment] 2019-09-09 19:33
I repro reliably with "https://googleplex-android-review.git.corp.google.com" - it very well may be related to how that specific URL line-wraps when the scrollbar is there.

Let me know when 1.0.6 is available in the chrome web store and I'll try it out (I seem to be stuck on 1.0.4).

**Comment by sdefresne** [comment] 2019-09-10 08:26
Version 1.0.7 is now available on the chrome web store (you may have to navigate to chrome://extensions, select the extension and then use the update button to force an update).

**Comment by nfischer** [comment] 2019-09-10 20:06
Verified the workaround does the job. I'm looking forward to using this helpful extension for Android reviews now too!

**Comment by eliptus-google** [comment] 2019-09-11 01:10
Looks good to me too. Thanks!
